### ISSUE TITLE
TODO List!

### ISSUE THREAD

**Issue by IsaiahPatton** [Bssentials/Bssentials#18]
Heres an todo list for Bssentials:
- [ ] Have all mobs in /spawnmob
- [ ] Add /item
- [ ] Add /permmission command
- [ ] Add Vault hook (eco system)
- [ ] Add /enchant
- [ ] Add /anvil
- [ ] Add /echest
- [ ] Add /exp
- [ ] Add /firework
- [ ] Add /hat
- [ ] Add /kit
- [ ] Add /skull
- [ ] Add /afk
- [ ] Add /recipe
- [ ] Add tpa system ( /tpa /tpahere /tpaccept /tpdeny )

**Comment by LongLiveBukkit** [comment]
/hat added in commit https://github.com/Bssentials/Bssentials/commit/81a175e335601c9b5da76c00138b599cc394b35b

**Comment by ramidzkh** [comment]
All mobs can be found using EntityType.values();

**Comment by pisaiah** [comment]
![image](https://user-images.githubusercontent.com/16439221/39403476-41e0ce16-4b4b-11e8-8875-a2bb3f21ff4a.png)
Working on adding full Essentials API support to Bssentials.

**Comment by Outfit8TSB** [comment]
```
[17:56:29 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+93-3a6fdd9
[17:56:30 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[17:56:30 INFO]: [Essentials] No kits found to migrate.
[17:56:30 INFO]: [Essentials] Loaded 39121 items from items.json.
[17:56:30 INFO]: [Essentials] Using locale ko_KR
[17:56:30 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[17:56:31 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[17:56:31 INFO]: [Essentials] Using superperms-based permissions.
[17:56:31 INFO]: [Bssentials] Enabling Bssentials v${full.version}*
[17:56:31 INFO]: [Bssentials] BSSENTIALS: ===========================
[17:56:31 INFO]: [Bssentials] BSSENTIALS: EssentialsX warps found!
[17:56:31 INFO]: [Bssentials] BSSENTIALS: To use your old warps move them from the /Essentials/warps/ folder into /Bssentials/warps/
[17:56:31 INFO]: [Bssentials] BSSENTIALS: ===========================
[17:56:31 WARN]: [Bssentials] Could not save config.yml to plugins\Bssentials\config.yml because config.yml already exists.
[17:56:31 WARN]: [Bssentials] Could not save info.txt to plugins\Bssentials\info.txt because info.txt already exists.
[17:56:31 WARN]: [Bssentials] Could not save motd.txt to plugins\Bssentials\motd.txt because motd.txt already exists.
[17:56:31 WARN]: [Bssentials] Could not save rules.txt to plugins\Bssentials\rules.txt because rules.txt already exists.
[17:56:31 INFO]: [Bssentials] Loading configuration...
[17:56:31 ERROR]: Error occurred while enabling Bssentials v${full.version} (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
        at Bssentials-Bukkit.jar/bssentials.include.YamlConfiguration$YamlRepresenter.<init>(YamlConfiguration.java:31) ~[Bssentials-Bukkit.jar:?]
        at Bssentials-Bukkit.jar/bssentials.include.YamlConfiguration.<init>(YamlConfiguration.java:27) ~[Bssentials-Bukkit.jar:?]
        at Bssentials-Bukkit.jar/bssentials.configuration.BssConfiguration.<init>(BssConfiguration.java:19) ~[Bssentials-Bukkit.jar:?]
        at Bssentials-Bukkit.jar/bssentials.configuration.Configs.initConfigs(Configs.java:13) ~[Bssentials-Bukkit.jar:?]
        at Bssentials-Bukkit.jar/bssentials.bukkit.BssentialsPlugin.onEnable(BssentialsPlugin.java:73) ~[Bssentials-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[radioactive-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[radioactive-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:630) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:579) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:447) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1158) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[radioactive-1.20.6.jar:1.20.6-DEV-5d2166a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:56:31 INFO]: [Bssentials] Disabling Bssentials v${full.version}
```
sorry for an off topic comment, but, i am having a serious problem.
